### ISSUE TITLE
TIFFReadDirectoryCheckOrder Warning Raised while running preprocessing.py on .svs files

### ISSUE THREAD

**Issue by ankit-21** [AIRMEC/im4MEC#4]
#### Description
While creating .h5 files using the preprocessing.py script, I encountered an error: 
TIFFReadDirectoryCheckOrder: Warning, Invalid TIFF directory; tags are not sorted in ascending order. 

This is a somewhat confusing warning/error as it seems to take a long time to process the specific error prone svs files and then the script times out without creating any .h5 file in the output folder.
I use "imagenet" weights to convert the .svs files to .h5 files to be utilized down the line. I encounter this issue with a small subset of .svs files that are generated in-house at our lab. I have looked at different forums and could not find a way to fix this issue. 

#### To Reproduce
python preprocess.py \
--input_slide /path/to/input_slide.svs \
--output_dir /path/to/output_folder \
--tile_size 360 \
--out_size 224 \
--batch_size 256 \
--backbone resnet50 \
--imagenet

It would be really helpful if you could look into this issue. 
Please let me know if you have any questions or need any additional information to solve this.

Thanks
Ankit

**Comment by jjhbw** [comment]
This seems like an error originating from Openslide which is used by `preprocess.py` to open the .svs files for reading. This is not something we can help with I'm afraid, as we don't control Openslide.

I found https://github.com/openslide/openslide/issues/228, which seems related. I recommend you ask your question there.

Closing because this is not something we can help with, sorry.
